name: Compare PostgreSQL Schemas

on:
  push:
    branches: [ main ]

jobs:
  compare-schemas:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install PostgreSQL
      run: sudo apt-get install postgresql-client -y

    - name: Dump dev and prod schemas
      env:
        DEV_DB_URL: ${{ secrets.DEV_DB_URL }}
        PROD_DB_URL: ${{ secrets.PROD_DB_URL }}
      run: |
        pg_dump --schema-only --no-owner --no-privileges "$DEV_DB_URL" > dev_schema.sql
        pg_dump --schema-only --no-owner --no-privileges "$PROD_DB_URL" > prod_schema.sql

    - name: Compare schemas
      run: |
        diff -u dev_schema.sql prod_schema.sql || echo "Schemas are different!"
